name: sizzle
version: 0.2.0.0
github: "shafik23/sizzle"
license: BSD3
author: "Shafik Amin"
maintainer: "shafik23@gmail.com"
copyright: "2020"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Education

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/shafik23/sizzle#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - microlens-platform
  - transformers
  - mtl
  - random
  - text
  - http-conduit
  - bytestring
  - scotty
  - cookie
  - wai
  - wai-extra
  - wai-middleware-static
  - blaze-builder
  - digestive-functors

default-extensions:
  - OverloadedStrings

library:
  source-dirs: src

executables:
  sizzle-exe:
    when:
      - condition: false
        other-modules: Paths_sizzle
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - sizzle

tests:
  sizzle-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - sizzle
