name:                sizzle
version:             0.1.0.0
github:              "shafik23/sizzle"
license:             BSD3
author:              "Shafik Amin"
maintainer:          "shafik23@gmail.com"
copyright:           "2020"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Education

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/shafik23/sizzle#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  sizzle-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sizzle

tests:
  sizzle-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sizzle
